### PR TITLE
blender export plugin version 2

### PR DESCRIPTION
**Pull request by vikasTmz**
Covers all new features raised in Issues: #3,#4,#5,#6,#7,#8,#11,#12 and #13.
The `tree view` UI implemented does not match the one implemented under scene hierarchy in blender since there doesn't exist a module for it, but has all the functionalities. `UIList` was used instead.

**Usage**:

- Same process as the plugin in previous PR.
- **Addition**: If `vertices/edges` are to given when `Type == "3D Faces" || "3D Lines"`, then select the necessary `vertices` from the object in the scene and click `Get Vertices`. This displays the list of selected `vertices`. 
- In the scene these selected `vertices` are separated and a new `mesh` is created. A `face` is then constructed for this `mesh`.
Note: The `vertices` are **not editable** in the display panel. Use `undo` to revert any changes.
- Enable/Disable the primitives from the `tree view` before exporting. All are enabled by default.
- To edit a primitive:
               1. Select it from the `tree view` and click `Select List Item`.
               2. The properties can be edited in the `ViSP CAD Properties Panel`.

**TODO**:

- Error handling.

### CODE REVIEW

**Comment by fspindle** [comment]
I have a strange error when I open blender, enter in edit mode and select `get vertices` on a 3D face feature

capture

**Comment by s-trinh** [comment]
@vikasTmz Nice work, nice solution.
@fspindle Did you try to select only the (4) points that belong to a face?

**Comment by fspindle** [comment]
@s-trinh You are right, this was my issue
I don't know if it would be possible to detect this user bad usage and print a nicer warning

**Comment by vikasTmz** [comment]
@fspindle The error was form the statement `bpy.ops.mesh.edge_face_add()`, which was called even when no missing faces were present from the selected vertices.
There may be some more cases where error handling should be done. I'll fix these now, but besides that is there any improvements?

**Comment by fspindle** [comment]
Yes, with @s-trinh we just reviewed your work. Nice beginning. We identify some improvements that could be achieved. He will give you the complete list asap.

From a user point of view, if I introduce basically 
- a circle  I would be able to retrieve the coordinates or the point 1 (which is in fact the center of the circle) and the radius just selecting 3 points in `edit mode` and pressing a new button named "Calculate center&radius" or something like that
- a cylinder I would be able to compute the coordinates of the point 1 or 2 (which are 2 points on the cylinder revolution axis) and the radius just by selecting 3 points on the circle

**Comment by s-trinh** [comment]
**cc** @fspindle Can you take a look and correct me or add something I could have missed?

Some errors we encountered:
- when we want to clear the list of face primitives, we get the following error message when clicking on "Clear List":
error_clear_list
- we get an error when we want to remove ("minus" button) a primitive from a list: 
error_remove_from_list
- we did not manage to export 3D lines (select 2 points, Get Vertices, Add Properties) (3D Faces from lines work but this feature is less important than the possibility to model single 3D lines)

---

Improvements / new features suggestion:
- remove optional buttons in the user interface (if possible):
  - "Enable For Export" checkbox button looks not useful, especially if we have the feature to enable or disable individual primitive later
  - this contextual menu should be removed (right click on an object in a list):
contextual_menu
  - if possible, instead customize the contextual menu to add the following options: enable or disable this primitive, remove this primitive from the list
  - if possible, remove these buttons and replaced them by a scroll bar to navigate between the primitives in the list:
buttons_navigation
- is it possible to add some tooltips to a button in Blender?
- not very important, at the export, is it possible to write first the points for 3D lines, then for 3D faces, 3D cylinders and for 3D circles? This way, the order matches the primitive order in the tutorial and we get increasing point indexes to model each primitive type

---

Circle modeling improvement:
- add the possibility to model a circle when the center of the circle is not accessible
- UI design suggestion:
circle_modelling_ui
  - rename Point1 (and also for Point2 and 3 if you find a better wording, these points are used only to calculate the normal of the circle for visibility and do not need to be on the circumference of the circle) to something more meaningful
  - add a tooltip or a way to say that "Calculate radius" needs 2 points
  - add another button to calculate the center of a circle + the radius when the user select 3 points on the circle circumference (e.g. when the center of the circle is not accessible), pressing this button should update the center coordinate fields and the radius field

---

Cylinder modeling improvement:
- similar to the circle case, add the possibility to model a cylinder when the two points at the extremity of the axis of the revolution of the cylinder are not accessible
- UI design suggestion:
cylinder_modelling_ui
  - rename Point 1 and Point 2 to something more meaningful (e.g. axis revolution point 1 and 2?)
  - add a tooltip or a way to say that "Calculate Radius" needs two points
  - add a button to calculate the axis revolution point 1 and the cylinder radius from 3 points on the cylinder circumference (e.g. when the center of the "circles" of the cylinder are not accessible)
  - add a button to calculate the axis revolution point 2 from 2 points (or 3 points for more precision?) on the cylinder circumference

What is the purpose of the button "load previous property"? It looks a little bit confusing.

**Comment by fspindle** [comment]
At @s-trinh thanks this is what we discussed.

After a good night, I have a new suggestion to simplify the GUI:

---

For a circle one column with
````
Text: Center
coord x value
coord y value
coord z value
Text: Radius
radius value
Button: Update
````
The button `Update` updates the values from the selection of points in `edit mode` 
- When 1 point is selected, we update the coords of the center
- When 2 points are selected we update the radius (half distance between the 2 points)
- When 3 points are selected (on the circle circumference) we update the radius and the coordinates of the center
- When 0 points are selected we display a message "No point selected" or something similar
- When more than 3 points selected we display a message "Cannot update circle from more than 3 points"

---

For a cylinder 3 blocks (may be organised vertically in 1 column)

In the first block
````
Text: Axis revolution point 1
coord x value
coord y value
coord z value
Button: Update
````
The button `Update` updates the values from the selection of points in `edit mode` 
- When 1 point is selected, we update the coords of point 1
- When 3 points are selected (on the circle circumference) we update the radius and the coordinates of point 1
- When 0 points are selected we display a message "No point selected" or something similar
- When more than 3 points selected we display a message "Cannot update axis revolution point and radius from more than 3 points"


In the second block
````
Text: Axis revolution point 2
coord x value
coord y value
coord z value
Button: Update
````
The button `Update` updates the values from the selection of points in `edit mode` 
- When 1 point is selected, we update the coords of point 2
- When 3 points are selected (on the circle circumference) we update the radius (meaning erase the value potentially set in block 1 when 3 points were selected) and the coordinates of point 2
- When 0 points are selected we display a message "No point selected" or something similar
- When more than 3 points selected we display a message "Cannot update axis revolution point and radius from more than 3 points"

In the third block
````
Text: Radius
radius value
Button: Update
````
The button `Update` updates the values from the selection of points in `edit mode` 
- When 2 points are selected we update the radius (half distance between the 2 points)
- When the number of points that are selected differ from 2 we display a message "Cannot update  radius when the number of selected points differ from 2"

What do you think ?

**Comment by s-trinh** [comment]
It's good for me.

**Comment by vikasTmz** [comment]
This should work. I'll see if I can add these instructions as a tool tip next to the respective buttons/fields.

**Comment by vikasTmz** [comment]
Why are three points needed when the two points that are diametrically opposite are given to calculate radius can also be used to get the center?

**Comment by fspindle** [comment]
Ok, with 2 points on the diameter you can compute the radius + center (good idea). But sometimes it could be difficult for the user to be sure that the 2 points belong to the diameter.

Introducing 3 points selection allows the user to select any point on the circumference. Then on the web you will find the equations (I found for example  https://math.stackexchange.com/questions/1076177/3d-coordinates-of-circle-center-given-three-point-on-the-circle and the the radius could be obtained from the center and on the points)

**Comment by fspindle** [comment]
Nice thanks. From a quick tour, I would  suggest to introduce a `Clear` button to erase all the values (radius + center coords)  for a circle and the same for a cylinder.

Selecting a 3D face and pressing `-` to erase the face change the focus to the 3D cylinder event if there are remaining 3D faces

**Comment by vikasTmz** [comment]
> we did not manage to export 3D lines 

This has been fixed. I only considered meshes with faces initially.

> this contextual menu should be removed 

This contextual menu is blender's generic right click menu that is showed on any event. I believe the contents of this menu are hard-coded though the latest version has a patch to add options to this menu. But this would then be visible on RMB click on any UI button, field etc.

I'll have to look further though to be sure if this is not possible

**Comment by vikasTmz** [comment]
Should I now proceed with exporting hierarchical models and setting LOD parameters?

**Comment by fspindle** [comment]
We prefer that you add 2 tutorials (text + screnshot + video) :
- one to show how to use the plugin on simple objects (cube, circle, cylinder) exporting the corresponding CAD model
- an other to show how to simplify a complex model and export. A good candidate is the cubesat model
- the hierarchical model + lod in blender is optional, and could be introduced at the end of the project if it remains time

Then  what we see is the developement of the Qt GUI to be able to load a cao model, display the normal of the faces. Allow to set some properties (lod, name of the face) + something to change the normal if requested by the user

**Comment by fspindle** [comment]
Nice job.

Below some improvement suggestions:

1. In the exported .cao, the comment `# 3D points` should be placed after the line `V1`
```` 
V1
# 3D points
0
# 3D lines
...
````

2. Concerning the `3D Lines` they are always exported as 3D lines (ok) **AND** 3D faces (should be optional)
````
V1
3
# 3D points
1.000000 -1.000000 -1.000000
1.000000 1.000000 -0.999999
0.999999 1.000000 1.000001
# 3D lines
3
1 2
2 0
0 1
# Faces from 3D lines
1
3 0 1 2
````

Since sometimes it could be interesting to track only lines (mbt edges), nor the keypoints that belong to the face defined by the lines, I suggest that we add someting to enable/disable (may be a check button ?) the face export from lines to allow:

````
V1
3
# 3D points
1.000000 -1.000000 -1.000000
1.000000 1.000000 -0.999999
0.999999 1.000000 1.000001
# 3D lines
3
1 2
2 0
0 1
# Faces from 3D lines
0
````

**Comment by vikasTmz** [comment]
Done. #9  and #10.

Also is there an issue if duplicate edge keys are present under `#3D Lines` ? In case there is a face, I'm getting the `edge_key_map` by iterating over each face(polygon) of the mesh. So edges that are common for faces are repeated.

Eg:-

```
V1
# 3D points
8
1.000000 -1.000000 -1.000000
1.000000 -1.000000 1.000000
-1.000000 -1.000000 1.000000
-1.000000 -1.000000 -1.000000
....
# 3D lines
16
0 1
1 2
2 3
3 0
2 1 (repeated)
....
```

**Comment by vikasTmz** [comment]
Any other changes for this PR?

>  something to change the normal

This can be done in blender too for every face.

**Comment by s-trinh** [comment]
> something to change the normal
> This can be done in blender too for every face.

Feel free to do it if the feature can be implemented easily. Otherwise it can be future improvement for the end of the project.

I did a quick test:
I noticed that the object scale is not taken into account when a primitive is created in the scene. Also, I think that global or local frame should be also taken into account when getting the point coordinate.

I will experiment more in depth and give you a summary soon.

**Comment by s-trinh** [comment]
> Also is there an issue if duplicate edge keys are present under #3D Lines ? In case there is a face, I'm getting the edge_key_map by iterating over each face(polygon) of the mesh. So edges that are common for faces are repeated.
> 
> Eg:-
> 
> V1
> #3D points
> 8
> 1.000000 -1.000000 -1.000000
> 1.000000 -1.000000 1.000000
> -1.000000 -1.000000 1.000000
> -1.000000 -1.000000 -1.000000
> ....
> #3D lines
> 16
> 0 1
> 1 2
> 2 3
> 3 0
> 2 1 (repeated)
> ....

Duplicated segments like in your example is not a problem. Moreover, the order of the points will define the visibility of the face.
Demo of the tracking of a cube:

output

The model file is:
```
# Blender v2.78 (sub 0) CAO File
V1
# 3D points
8
1.000000 -1.000000 -1.000000
1.000000 -1.000000 1.000000
-1.000000 -1.000000 1.000000
-1.000000 -1.000000 -1.000000
1.000000 1.000000 -0.999999
0.999999 1.000000 1.000001
-1.000000 1.000000 1.000000
-1.000000 1.000000 -1.000000
# 3D lines
24
0 1
1 2
2 3
3 0
4 7
7 6
6 5
5 4
0 4
4 5
5 1
1 0
1 5
5 6
6 2
2 1
2 6
6 7
7 3
3 2
4 0
0 3
3 7
7 4
# Faces from 3D lines
6
4 0 1 2 3
4 4 5 6 7
4 8 9 10 11
4 12 13 14 15
4 16 17 18 19
4 20 21 22 23
# Faces from 3D points
0
# 3D cylinders
0
# 3D circles
0
```

**Comment by s-trinh** [comment]
Another experiment with the modelling and the tracking of a cylinder + circle:
output

So far, the issues I noticed:

- the object scale is not taken into account
- if the primitive name is changed, there is an error at the export
- maybe try to take also into account if the `Global ` or `Local` coordinate is selected
- for the circle, it is no more possible to select the first and second point, useful to define the circle visibility using the order of the points
- maybe an option to switch the points order for the 3D face and the 3D circle primitives and the possibility to display the normal in Blender?

**Comment by vikasTmz** [comment]
> - if the primitive name is changed, there is an error at the export
> - maybe try to take also into account if the Global or Local coordinate is selected

Fixed

> - the object scale is not taken into account
> - for the circle, it is no more possible to select the first and second point, useful to define the circle visibility using the order of the points

Could you elaborate these two points?

**Comment by s-trinh** [comment]
> - the object scale is not taken into account

For instance, if we change the dimension of the cube, the point coordinates are still between -1 and 1 but the scale of the object has changed. The coordinates should be scaled accordingly for me.

blender_scale


> - for the circle, it is no more possible to select the first and second point, useful to define the circle visibility using the order of the points

The order of the 3 points used to model the circle (circle center + 2 points on the circle plane) is used to determine the normal of the circle and thus is used for the visibility test (see [here](http://visp-doc.inria.fr/doxygen/visp-daily/tutorial-tracking-mb.html#mb_advanced_cao_cir)).
I think it is the same issue than with the 3D face case: we cannot retrieve the order of the selected points in the list. 
A button to switch the two point coordinates could do the trick maybe?

**Comment by vikasTmz** [comment]
> For instance, if we change the dimension of the cube, the point coordinates are still between -1 and 1 but the scale of the object has changed. The coordinates should be scaled accordingly for me.

Was this scale applied in `Object Mode`? In blender scaling an object in `Object Mode` doesn't change the mesh, thus the vertices remain the same. This has to be done in `Edit Mode`.

This [link](https://blender.stackexchange.com/questions/28558/scaling-in-object-and-edit-mode) covers more reasons.

**Comment by s-trinh** [comment]
Yes it is in `Object Mode`. Apply the scale command should solve the issue. Maybe we should add this instruction in the tutorial, as a note.

**Pull request merged**
