### PR TITLE
Qt final week

### PR DESCRIPTION
**Pull request by vikasTmz**
### TODO:
- [x] Parse correctly generic CAO model (see here)
- [x] Save `Qt3DRender::QCamera` Settings into XML config file.
- [ ] Display face normals.
- [ ] Switch model points when the displayed face normal is not correct.
- [x] Choose the 3D points for the init config file.
- [x] Exporting Multiple models.
- [ ] Fix bug: "run the application --> import CAO + save dialog make the application crash"
- [ ] Update README/Documentation for Qt-App.
- [ ] Remove unused icons.
- [ ] Help button.
- [ ] Get lod settings (length & area) using camera intrinsic & extrinsic properties & world coord.

### CODE REVIEW

**Comment by s-trinh** [comment]
Looks like in `Qt3DRender::QObjectPicker *createObjectPickerForEntity(Qt3DCore::QEntity *entity);` function signature, the returned pointer is not used. If so, you can remove the return.

The `QObjectPicker` in Qt3D seems still buggy in this Qt version (5.9.1)? I have some issues to correctly select the init point and not set the face properties. It works with some difficulties. I repaste your [link](https://forum.qt.io/topic/77570/qt3d-qobjectpicker-test-not-working-as-expected) for improvement / test in the future.

If you have some time at the end, some improvements:

- there should be an option to change the sphere radius to select the init points
- do not add the same init point if the user click multiple of times on the same sphere

**Comment by vikasTmz** [comment]
I was planning to finish some of these tasks before this branch got merged, or should I make a new PR?

**Comment by s-trinh** [comment]
You can just open another PR and add the corresponding link in the Wiki [page](https://github.com/lagadic/visp_cao_editor/wiki/GSoC-2017-with-ViSP).

**Comment by fspindle** [comment]
Sorry, we did the merge before asking you.
I think that a new PR would be perfect.

**Pull request merged**
